# Generated by Django 4.1.7 on 2023-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Header Icon Image')),
                ('title1', models.CharField(max_length=20, verbose_name='Title-1')),
                ('title2', models.CharField(max_length=20, verbose_name='Title-2')),
                ('title3', models.CharField(max_length=20, verbose_name='Title-3')),
                ('subtitle1', models.CharField(max_length=20, verbose_name='Title-3')),
                ('subtitle2', models.CharField(max_length=20, verbose_name='Title-3')),
                ('title4', models.CharField(max_length=20, verbose_name='Title-4')),
                ('btn_name', models.CharField(max_length=25, verbose_name='Button Name')),
            ],
        ),
    ]
