# Generated by Django 4.1.7 on 2023-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='SubTitle')),
                ('btn_name', models.CharField(max_length=25, verbose_name='Button Name')),
                ('check_btn', models.BooleanField(verbose_name='Check Button')),
            ],
        ),
    ]
