# Generated by Django 4.1.7 on 2023-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='check_btn',
        ),
        migrations.AddField(
            model_name='title',
            name='title2',
            field=models.CharField(default=1, max_length=40, verbose_name='Title-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title3',
            field=models.CharField(default=1, max_length=40, verbose_name='Title-3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title4',
            field=models.CharField(default=1, max_length=40, verbose_name='Title-4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title-1'),
        ),
    ]
