# Generated by Django 4.1.7 on 2023-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_title_check_btn_title_title2_title_title3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='title5',
            field=models.CharField(default=1, max_length=40, verbose_name='Title-5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=40, verbose_name=''),
        ),
    ]
