# Generated by Django 4.1.7 on 2023-03-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_title_title_title_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title1',
            new_name='title',
        ),
    ]
