# Generated by Django 4.1.7 on 2023-03-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_title1_title_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=50, verbose_name='Contact Title')),
                ('subtitle1', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('subtitle_info1', models.CharField(max_length=30, verbose_name='Phone Info')),
                ('subtitle2', models.CharField(max_length=20, verbose_name='Email')),
                ('subtitle_info2', models.EmailField(max_length=254, verbose_name='Email Info')),
                ('subtitle3', models.CharField(max_length=25, verbose_name='Location')),
                ('subtitle_info3', models.CharField(max_length=60, verbose_name='Location Info')),
                ('title2', models.CharField(max_length=40, verbose_name='Contact Title 2')),
                ('btn_name', models.CharField(max_length=20, verbose_name='Button Name')),
            ],
        ),
    ]
