# Generated by Django 4.1.7 on 2023-03-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactget',
            old_name='tilte',
            new_name='title',
        ),
    ]
