# Generated by Django 4.1.7 on 2023-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_tilte_contactget_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40, verbose_name='User Name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('company_name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('user_message', models.TextField(verbose_name='User Message')),
            ],
        ),
    ]
