# Generated by Django 4.1.7 on 2023-03-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_headernavbar_remove_header_subtitle1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderNavbar',
        ),
        migrations.AddField(
            model_name='header',
            name='subtitle1',
            field=models.CharField(default=1, max_length=20, verbose_name='Title-3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='subtitle2',
            field=models.CharField(default=1, max_length=20, verbose_name='Title-3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='title1',
            field=models.CharField(default=1, max_length=20, verbose_name='Title-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='title2',
            field=models.CharField(default=1, max_length=20, verbose_name='Title-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='title3',
            field=models.CharField(default=1, max_length=20, verbose_name='Title-3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='title4',
            field=models.CharField(default=1, max_length=20, verbose_name='Title-4'),
            preserve_default=False,
        ),
    ]
