# Generated by Django 4.1.7 on 2023-03-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='About Content Image')),
                ('name', models.CharField(max_length=20, verbose_name='About Content Name')),
                ('profession', models.CharField(max_length=80, verbose_name='About Content Profession')),
                ('social', models.CharField(max_length=80, verbose_name='About Content social')),
                ('symbol_img', models.ImageField(upload_to='images', verbose_name='About Content Verified')),
            ],
        ),
    ]
