# Generated by Django 4.1.7 on 2023-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_about_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=80, verbose_name='About Content Profession')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(max_length=80, verbose_name='About Content social')),
            ],
        ),
        migrations.RemoveField(
            model_name='about_content',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='about_content',
            name='social',
        ),
    ]
