# Generated by Django 4.1.7 on 2023-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_aboutprofession_aboutsocial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutProfession',
        ),
        migrations.DeleteModel(
            name='AboutSocial',
        ),
        migrations.AddField(
            model_name='about_content',
            name='profession',
            field=models.CharField(default=1, max_length=80, verbose_name='About Content Profession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_content',
            name='social',
            field=models.CharField(default=1, max_length=80, verbose_name='About Content social'),
            preserve_default=False,
        ),
    ]
