# Generated by Django 4.1.7 on 2023-03-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_aboutprofession_delete_aboutsocial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastestEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Lates Episodes Title')),
                ('img', models.ImageField(upload_to='images', verbose_name='Lastest First Image')),
                ('btn_name', models.CharField(max_length=25, verbose_name='Latest Episodes Button')),
                ('minutes', models.CharField(max_length=30, verbose_name='Latest Episodes Minutes')),
                ('episodes', models.CharField(max_length=30, verbose_name='Latest Episodes')),
                ('subtitle', models.CharField(max_length=30, verbose_name='Latest Episodes Subtitle')),
                ('user_img', models.ImageField(upload_to='images', verbose_name='Latest Episodes Immage')),
                ('name_profession', models.CharField(max_length=30, verbose_name='Latest Episodes name and prof')),
                ('text', models.CharField(max_length=50, verbose_name='Latest Episodes Text')),
                ('airpods', models.CharField(max_length=10, verbose_name='Latest Episodes Airpods')),
                ('likes', models.CharField(max_length=10, verbose_name='Latest Episodes Likes')),
                ('comments', models.CharField(max_length=10, verbose_name='Latest Episodes Comments')),
                ('downloads', models.CharField(max_length=10, verbose_name='Latest Episodes Downloads')),
            ],
        ),
        migrations.AlterField(
            model_name='about_content',
            name='profession',
            field=models.TextField(verbose_name='About Content Profession'),
        ),
    ]
