# Generated by Django 4.1.7 on 2023-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_lastestepisodes_alter_about_content_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastestepisodes',
            name='title',
        ),
        migrations.AlterField(
            model_name='lastestepisodes',
            name='user_img',
            field=models.ImageField(upload_to='images', verbose_name='Latest Episodes Image'),
        ),
    ]
