# Generated by Django 4.1.7 on 2023-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_lastestepisodes_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastestepisodes',
            name='symbol_img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='About Content Verified'),
            preserve_default=False,
        ),
    ]
