# Generated by Django 4.1.7 on 2023-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_lastestepisodes_symbol_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Lastest First Image')),
                ('title', models.CharField(max_length=25, verbose_name='Latest Episodes Button')),
                ('minutes', models.CharField(max_length=30, verbose_name='Latest Episodes Minutes')),
                ('episodes', models.CharField(max_length=30, verbose_name='Latest Episodes')),
                ('subtitle', models.CharField(max_length=30, verbose_name='Latest Episodes Subtitle')),
                ('user_img', models.ImageField(upload_to='images', verbose_name='Latest Episodes Image')),
                ('name_profession', models.CharField(max_length=30, verbose_name='Latest Episodes name and prof')),
                ('text', models.CharField(max_length=50, verbose_name='Latest Episodes Text')),
                ('airpods', models.CharField(max_length=10, verbose_name='Latest Episodes Airpods')),
                ('likes', models.CharField(max_length=10, verbose_name='Latest Episodes Likes')),
                ('comments', models.CharField(max_length=10, verbose_name='Latest Episodes Comments')),
                ('downloads', models.CharField(max_length=10, verbose_name='Latest Episodes Downloads')),
                ('symbol_img', models.ImageField(upload_to='images', verbose_name='About Content Verified')),
            ],
        ),
        migrations.RemoveField(
            model_name='lastestepisodes',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='lastestepisodes',
            name='subtitle',
        ),
    ]
