# Generated by Django 4.1.7 on 2023-03-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_trendingepisodes_remove_lastestepisodes_episodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingepisodes',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='trendingepisodes',
            name='minutes',
        ),
        migrations.AlterField(
            model_name='trendingepisodes',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Latest Episodes Title'),
        ),
    ]
