# Generated by Django 4.1.7 on 2023-03-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_trendingepisodes_episodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingepisodes',
            name='subtitle',
        ),
    ]
