# Generated by Django 4.1.7 on 2023-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_trendingepisodes_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingepisodes',
            name='downloads',
        ),
        migrations.AlterField(
            model_name='trendingepisodes',
            name='user_img',
            field=models.ImageField(upload_to='images', verbose_name='Latest Episodes Images'),
        ),
    ]
