# Generated by Django 4.1.7 on 2023-03-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_trendingepisodes_downloads_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingepisodes',
            old_name='user_img',
            new_name='user_img2',
        ),
    ]
