# Generated by Django 4.1.7 on 2023-03-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_trendingepisodes_check_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastestepisodes',
            name='title',
            field=models.CharField(default=1, max_length=35, verbose_name='Latest Episodes Minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastestepisodes',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='Latest First Image'),
        ),
    ]
