# Generated by Django 4.1.7 on 2023-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='title1',
            field=models.CharField(max_length=80, verbose_name='Title-1'),
        ),
    ]
