# Generated by Django 4.1.7 on 2023-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_inch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=30, verbose_name='Detail Title')),
                ('img', models.ImageField(upload_to='images', verbose_name='Detail Image')),
                ('play', models.CharField(max_length=25, verbose_name='Detail Play')),
                ('minute', models.CharField(max_length=25, verbose_name='Detail Minute')),
                ('episode', models.CharField(max_length=30, verbose_name='Detail Episode')),
                ('title2', models.CharField(max_length=30, verbose_name='Detail Title')),
                ('text1', models.TextField(verbose_name='Detail Text')),
                ('text2', models.TextField(verbose_name='Detail Text')),
                ('text3', models.TextField(verbose_name='Detail Text')),
            ],
        ),
        migrations.DeleteModel(
            name='Inch',
        ),
    ]
