# Generated by Django 4.1.7 on 2023-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_detailcontent_delete_inch'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcontent',
            name='name',
            field=models.CharField(default=1, max_length=40, verbose_name='Detail Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailcontent',
            name='social',
            field=models.CharField(default=1, max_length=50, verbose_name='Detail Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailcontent',
            name='symbol_img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Detail Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailcontent',
            name='user_img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Detail User Image'),
            preserve_default=False,
        ),
    ]
