# Generated by Django 4.1.7 on 2023-03-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_detailcontent_name_detailcontent_social_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_email', models.EmailField(max_length=254, verbose_name='User Subscribe Email')),
            ],
        ),
    ]
