# Generated by Django 4.1.7 on 2023-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastestepisode',
            name='episodes',
            field=models.CharField(default=1, max_length=40, verbose_name='Latest Episodes'),
            preserve_default=False,
        ),
    ]
