# Generated by Django 4.1.7 on 2023-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_lastestepisode_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastestepisode',
            name='general_title',
            field=models.CharField(default=1, max_length=30, verbose_name='Latest Episode General Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendingepisode',
            name='general_title',
            field=models.CharField(default=1, max_length=30, verbose_name='Trending Episode General Title'),
            preserve_default=False,
        ),
    ]
