# Generated by Django 4.1.7 on 2023-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_lastestepisode_general_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='related_episodes',
            field=models.CharField(default=1, max_length=30, verbose_name='Related Episodes Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='topic_title',
            field=models.CharField(default=1, max_length=30, verbose_name='Topic Title'),
            preserve_default=False,
        ),
    ]
